language: node_js

node_js:
  - "8.0.0"

cache:
  directories:
    - node_modules 

install:
  - npm install

script:
  - npm test

after_success:
   - npm run coverage

branches:
  only:
    - master
