language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra
  cache:
    directories:
      - node_modules
  install:
    - npm install
    - cd android && gradlew.bat
  script:
    - npm test
  branches:
    only:
      - master
