language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra
  cache:
    directories:
      - node_modules
  before-install:
    - yes | sdkmanager "platforms;android-27"
  install:
    - npm install
  script:
    - ./gradlew build connectedCheck
    - npm test
  branches:
    only:
      - master
