language: node_js

node_js:
  - "10.0.0"

cache:
  directories:
    - node_modules 

install:
  - npm install

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

script:
  - npm test

#after_success:
   #- npm run coverage

branches:
  only:
    - master
