language: node_js

node_js:
  - "8.0.0"

cache:
  directories:
    - node_modules

before_install:
   - curl -o- -L https://yarnpkg.com/install.sh | bash -s -
   - export PATH="$HOME/.yarn/bin:$PATH" 

install:
  - yarn install

script:
  - npm test

after_succes:
   - yarn coverage

branches:
  only:
    - master
