language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra
  cache:
    directories:
      - node_modules
  before-install:
    - node --version
    - cd andrpoid && ./gradle build connectedCheck
  install:
    - npm install
  script:
    - npm test
    - npm run build
  branches:
    only:
      - master
