language: android
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra
  cache:
    directories:
      - node_modules
  before-install:
    - yes | sdkmanager "platforms;android-23"
  install:
    - npm install
    - cd android && gradle assemble && ./gradlew assemble
  script:
    - cd android && gradle check && ./gradlew check 
    - npm test
  branches:
    only:
      - master
